# Generated by Django 5.1.7 on 2025-04-01 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Burial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('admin_description', models.TextField(blank=True, null=True, verbose_name='Описание администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Захоронение',
                'verbose_name_plural': 'Захоронения',
            },
        ),
        migrations.CreateModel(
            name='Cemetery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Кладбище',
                'verbose_name_plural': 'Кладбища',
            },
        ),
        migrations.CreateModel(
            name='BurialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Причина отклонения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('approved_burial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='core.burial', verbose_name='Одобренное захоронение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burial_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('cemetery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burial_requests', to='core.cemetery', verbose_name='Кладбище')),
            ],
            options={
                'verbose_name': 'Запрос на добавление',
                'verbose_name_plural': 'Запросы на добавление',
            },
        ),
        migrations.AddField(
            model_name='burial',
            name='cemetery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burials', to='core.cemetery', verbose_name='Кладбище'),
        ),
        migrations.CreateModel(
            name='FavoriteBurial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('burial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.burial', verbose_name='Захоронение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное захоронение',
                'verbose_name_plural': 'Избранные захоронения',
            },
        ),
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('burial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notes', to='core.burial', verbose_name='Захоронение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заметка пользователя',
                'verbose_name_plural': 'Заметки пользователей',
            },
        ),
        migrations.AddIndex(
            model_name='burial',
            index=models.Index(fields=['full_name'], name='core_burial_full_na_5668fc_idx'),
        ),
        migrations.AddIndex(
            model_name='burial',
            index=models.Index(fields=['birth_date'], name='core_burial_birth_d_003aec_idx'),
        ),
        migrations.AddIndex(
            model_name='burial',
            index=models.Index(fields=['death_date'], name='core_burial_death_d_45f66f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteburial',
            unique_together={('user', 'burial')},
        ),
        migrations.AlterUniqueTogether(
            name='usernote',
            unique_together={('user', 'burial')},
        ),
    ]
