# Generated by Django 5.2 on 2025-04-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_description', models.TextField(verbose_name='предлагаемое описание')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='статус')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='причина отклонения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата предложения')),
            ],
            options={
                'verbose_name': 'предложение редактирования',
                'verbose_name_plural': 'предложения редактирования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteGrave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
            ],
            options={
                'verbose_name': 'избранное захоронение',
                'verbose_name_plural': 'избранные захоронения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Grave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon_coordinates', models.TextField(verbose_name='координаты полигона')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО погребенного')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='дата смерти')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
            ],
            options={
                'verbose_name': 'захоронение',
                'verbose_name_plural': 'захоронения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'личная заметка',
                'verbose_name_plural': 'личные заметки',
                'ordering': ['-updated_at'],
            },
        ),
    ]
