# Generated by Django 5.2 on 2025-04-08 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='editproposal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_proposals', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddField(
            model_name='favoritegrave',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_graves', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddField(
            model_name='grave',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_graves', to=settings.AUTH_USER_MODEL, verbose_name='добавлено администратором'),
        ),
        migrations.AddField(
            model_name='favoritegrave',
            name='grave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_marks', to='graves.grave', verbose_name='захоронение'),
        ),
        migrations.AddField(
            model_name='editproposal',
            name='grave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_proposals', to='graves.grave', verbose_name='захоронение'),
        ),
        migrations.AddField(
            model_name='personalnote',
            name='grave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_notes', to='graves.grave', verbose_name='захоронение'),
        ),
        migrations.AddField(
            model_name='personalnote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_notes', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritegrave',
            unique_together={('grave', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='personalnote',
            unique_together={('grave', 'user')},
        ),
    ]
