# Generated by Django 5.2 on 2025-04-09 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graves', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cemetery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название кладбища')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='адрес')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('coordinates', models.CharField(blank=True, max_length=100, null=True, verbose_name='координаты центра')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
            ],
            options={
                'verbose_name': 'кладбище',
                'verbose_name_plural': 'кладбища',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='grave',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='grave_photos/', verbose_name='фотография'),
        ),
        migrations.AddField(
            model_name='grave',
            name='cemetery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graves', to='graves.cemetery', verbose_name='кладбище'),
        ),
    ]
