# Generated by Django 5.2 on 2025-04-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('system', 'Системное уведомление'), ('edit_proposal', 'Предложение редактирования'), ('proposal_status', 'Статус предложения')], default='system', max_length=20, verbose_name='тип уведомления')),
                ('message', models.TextField(verbose_name='сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('related_id', models.IntegerField(blank=True, null=True, verbose_name='ID связанной сущности')),
            ],
            options={
                'verbose_name': 'уведомление',
                'verbose_name_plural': 'уведомления',
                'ordering': ['-created_at'],
            },
        ),
    ]
